### ISSUE TITLE
Create a guide: How to write a donor acknowledgement

### ISSUE THREAD

**Issue by mmaecruz** [hackforla/knowledgebase-content#103]
### Overview
We need to create a guide to making donor acknowledgement so that projects can thank donors quickly without having to get org approval for each letter.

### Action Items
The phases in the guide-making process are listed below. Each phase displayed in blue is linked to a wiki page with instructions on how to complete that phase. Open the wiki page in a new tab, copy the instructions for each part into the section labeled 'Tasks' at the bottom of this issue, and complete each task listed.
- [ ] [Gather Examples Solo](https://github.com/hackforla/guides/wiki/How-to-Gather-Examples:-Solo) (open in a new tab)
- [ ]  [Gather Examples Collaboratively](https://github.com/hackforla/guides/wiki/Phase-2-%E2%80%90-Gather-Examples-Collaboratively)
- [ ]  [Create a Guide Draft](https://github.com/hackforla/guides/wiki/How-to-Draft-a-Guide)
   - [ ]  If needed, create a template
- [ ]  [Have your guide peer reviewed](https://github.com/hackforla/guides/wiki/Peer-Reviews-for-Guides)
- [ ]  [Present your guide for leadership review](https://github.com/hackforla/guides/wiki/Submitting-Your-Guide-for-Leadership-Review)
### Tasks
- [ ] This is where you will copy instructions from the wiki page for the step you are currently on.

### Resources
- Refer to https://github.com/hackforla/product-management/issues/123 for how to write a guide and the guide template

**Comment by fchan218** [comment]
@Aditya23soni Please add link to the Google Drive Folder under resources. Use to this issue for reference:
- https://github.com/hackforla/knowledgebase-content/issues/100

**Comment by fchan218** [comment]
### Files that needs to be moved 

Guide [How To - Write a Donor Acknowledgement Letter](https://docs.google.com/document/d/1Zrk3Hi3ZNfYo1dpe1QYErc7OtVrWYfQse_n3sNVP8T8/edit?usp=sharing)
- This file will need to be moved to the knowledgebase content repo
