### ISSUE TITLE
Create a Guide/Template: making composite images in our HfLA guides

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/knowledgebase-content#93]
### Overview
We need to create a guide for making composite images in our HFLA guides so that all guides screenshots and header images can be consistent across all CoPs.

### Action Items
- [x] Gather examples of how other Hack for LA projects or volunteers have done this (if applicable), adding each example as a link in the resources section below
   - [x] Once done, remove the "Guide: Gather Examples" label and add the "Guide: Research" label
- [x] Research existing information about [name of item] in [relevant resources, articles, etc.]
   - [x] Once done, remove the "Guide: Research" label and add the "Guide: Draft Guide" label
- [x] Create a draft guide, either in markdown format in this issue or a google doc in the [ux/ui google drive](https://drive.google.com/drive/u/1/folders/1os-4KyGnL0SXIeyfoDICOEpG5CO_1MaV)
    - [x] Once done, remove the "Guide: Draft Guide" label and add the "Guide: Review Guide" label
- [x] Review the guide with UX/UI community of practice
   - [x] Once done, remove the "Guide: Review Guide" label and add the "Guide: Leadership Review" label
- [x] Present to the Hack for LA leadership team for sign off
   - [x] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Place Guide" label

### Resources
Update issue hackforla/UI-UX#15 with the name of item you are working on
### Resources/Instructions
[Make your screenshots and headers for your guide - TEMPLATE](https://docs.google.com/presentation/d/1xu_lYuucKkBKD9jWfLDZkEv3PkmIjcFEf0MnjEJdV5c/edit#slide=id.gcd1d3ada7a_0_31)
[Completed Template](https://docs.google.com/document/d/1OyPfKqUU7ZinhjMoRmsXywyZfME_Oo_hpC2Zdxlb310/edit#)

Original text: https://github.com/hackforla/knowledgebase-content/issues/93

**Comment by fchan218** [comment]
The linked [Completed Template](https://docs.google.com/document/d/1OyPfKqUU7ZinhjMoRmsXywyZfME_Oo_hpC2Zdxlb310/edit#) in this issue is the same document as the one linked in this issue: 
- https://github.com/hackforla/knowledgebase-content/issues/91

The document can be found in the Google drive folder [0091 Guide: Add Screenshots and Graphics to your Guide](https://drive.google.com/drive/folders/1aHlXg843mg_4NlauZi-r2ECBhFin6_KH)
