### ISSUE TITLE
Tracker: Templates & Guides

### ISSUE THREAD

**Issue by daniellex0** [hackforla/knowledgebase-content#97]
### Overview
This is an issue to track the templates and guides we have available at UI/UX Community of Practice

### Action Items

| Guide           | Template Link                                                                                                          | Issue                                                            | Status      |
| --------------- | ---------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- | ----------- |

### Resources/Instructions
[Spreadsheet Converter](https://tabletomarkdown.com/convert-spreadsheet-to-markdown/)
[Templates and Guides Google Sheet]()

**Comment by fchan218** [comment]
This issue is closed. Currently using project board [P: Guides:  Tracker of issues in CoPs](https://github.com/orgs/hackforla/projects/58/views/4) as tracker for issues
