### ISSUE TITLE
Create a Guide/Template: developing a UX Research plan - Depreciated

### ISSUE THREAD

**Issue by Andre310** [hackforla/knowledgebase-content#98]
### Overview
We need to create a UX Research plan topic guide to help UX Researchers learn to build and develop research questions.

### Action Items
- [ ] Gather existing information about research questions on HfLA
- [ ] Affinity mapping around resources
- [ ] Write a draft of guidance on using resources

### Resources/Instructions
[CFA Qual research guide](https://f.hubspotusercontent30.net/hubfs/5622333/CFA_QualitativeResearchGuide_v1.pdf)
[Existing HfLA project centered around research-BOP](https://github.com/codeforamerica/brigade-playbook/wiki/Process-overview)

[Developing a research plan draft](https://docs.google.com/document/d/1NP-ocqxpXJ__XZXDwkiTVIZlKy9yLOACnV2YaFcJBGU/edit?usp=sharing)

[GreenEarthOS Research Plan: Funder Analysis](https://docs.google.com/document/d/1tsHUusJK5bZWjeiSFOsfdwbC-u-rJxRtkKWbNB0E814/edit)

#### Contents
- Defining purpose/scope of the research
- Defining purpose/scope of individual questions
- Effective practices

**Comment by fchan218** [comment]
I have removed the shortcuts and folder in the google drive for this issue
